# Generated by Django 5.2.9 on 2025-12-04 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Short description of the event')),
                ('content', models.TextField(blank=True, help_text='Full event details (HTML supported)')),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('event_time', models.TimeField(help_text='Time of the event')),
                ('location', models.CharField(help_text='Event location', max_length=500)),
                ('location_url', models.URLField(blank=True, help_text='Google Maps or location URL', max_length=500, null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the event', null=True, upload_to='events/featured/')),
                ('is_published', models.BooleanField(default=True, help_text='Only published events are displayed')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured events appear prominently')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for event inquiries', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone for event inquiries', max_length=20, null=True)),
                ('registration_url', models.URLField(blank=True, help_text='Event registration URL', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', help_text='Type of media', max_length=20)),
                ('file', models.FileField(help_text='Media file', upload_to='events/media/')),
                ('title', models.CharField(blank=True, help_text='Title/name for the media', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the media')),
                ('order', models.IntegerField(default=0, help_text='Order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Event this media belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Media',
                'verbose_name_plural': 'Event Media',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
