# Generated by Django 4.2.7 on 2025-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('careers', 'Careers'), ('articles', 'Articles & News'), ('legal', 'Legal Notice'), ('help_center', 'Help Center'), ('faq', 'FAQ'), ('forum', 'Forum'), ('custom', 'Custom Page')], default='custom', max_length=20),
        ),
    ]
