# Generated by Django 4.2.7 on 2025-12-04 04:59

import config.firebase_storage_backend
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the page', null=True, storage=config.firebase_storage_backend.FirebaseStorage(location='pages/featured'), upload_to='pages/featured/'),
        ),
        migrations.CreateModel(
            name='PageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video')], default='image', max_length=20)),
                ('file', models.FileField(help_text='Media file (image, document, or video)', storage=config.firebase_storage_backend.FirebaseStorage(location='pages/media'), upload_to='pages/media/')),
                ('title', models.CharField(blank=True, help_text='Title/name for the media', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the media')),
                ('order', models.IntegerField(default=0, help_text='Order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='pages.page')),
            ],
            options={
                'verbose_name': 'Page Media',
                'verbose_name_plural': 'Page Media',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
