# Generated by Django 5.2.9 on 2025-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_featured_image_pagemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Allow comments (for forum)'),
        ),
        migrations.AddField(
            model_name='page',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Application deadline (for careers)', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='application_email',
            field=models.EmailField(blank=True, help_text='Application email (for careers)', max_length=254),
        ),
        migrations.AddField(
            model_name='page',
            name='application_url',
            field=models.URLField(blank=True, help_text='Application URL (for careers)'),
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.CharField(blank=True, help_text='Author name (for articles)', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='author_email',
            field=models.EmailField(blank=True, help_text='Author email (for articles)', max_length=254),
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(blank=True, help_text='Category (for articles/help center)', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='document_type',
            field=models.CharField(blank=True, help_text='Document type (for legal)', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Effective date (for legal)', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date (for legal)', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='faq_items',
            field=models.JSONField(blank=True, default=list, help_text="FAQ items: [{'question': '', 'answer': ''}]"),
        ),
        migrations.AddField(
            model_name='page',
            name='forum_category',
            field=models.CharField(blank=True, help_text='Forum category (for forum)', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title (for careers)', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='job_type',
            field=models.CharField(blank=True, help_text='Job type: Full-time, Part-time, Contract (for careers)', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='location',
            field=models.CharField(blank=True, help_text='Job location (for careers)', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='related_pages',
            field=models.ManyToManyField(blank=True, help_text='Related pages (for help center)', to='pages.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='salary_range',
            field=models.CharField(blank=True, help_text='Salary range (for careers)', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (for articles)', max_length=500),
        ),
        migrations.AlterField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image (for articles)', null=True, upload_to='pages/'),
        ),
    ]
