# Generated by Django 4.2.7 on 2025-12-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_allow_comments_page_application_deadline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageMedia',
        ),
    ]
