# Generated by Django 4.2.7 on 2025-12-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_pagemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='department',
            field=models.CharField(blank=True, help_text='Department (for careers)', max_length=100),
        ),
    ]
