# Generated by Django 4.2.7 on 2025-12-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_heroimage'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingrequest',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests', to='properties.property'),
        ),
    ]
