# Generated by Django 4.2.7 on 2025-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_viewingrequest_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingrequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewingrequest',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
