# Generated by Django 4.2.7 on 2025-12-04 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Job title (e.g., 'Senior Real Estate Agent')", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=200, unique=True)),
                ('department', models.CharField(help_text="Department (e.g., 'Sales', 'Marketing', 'Operations')", max_length=100)),
                ('location', models.CharField(help_text="Job location (e.g., 'Nairobi, Kenya' or 'Remote')", max_length=200)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', help_text='Type of employment', max_length=20)),
                ('description', models.TextField(help_text='Detailed job description (HTML supported)')),
                ('short_description', models.TextField(blank=True, help_text='Brief summary of the position for listings', max_length=500)),
                ('requirements', models.TextField(blank=True, help_text='Required qualifications and skills (HTML supported)')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities (HTML supported)')),
                ('salary_range', models.CharField(blank=True, help_text="Salary range (e.g., '$50,000 - $70,000' or 'Competitive')", max_length=100)),
                ('application_email', models.EmailField(blank=True, help_text='Email address for applications (if different from default)', max_length=254)),
                ('application_url', models.URLField(blank=True, help_text='External URL for application (optional)')),
                ('is_active', models.BooleanField(default=True, help_text='Only active job postings are displayed')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured jobs appear at the top of listings')),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when job was posted')),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Application deadline (leave empty for no deadline)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-is_featured', '-posted_date', '-created_at'],
            },
        ),
    ]
