# Generated by Django 5.2.8 on 2025-12-02 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text="List of amenities like ['WiFi', 'Pool', 'Parking']"),
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('KSH', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='KSH', max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='is_for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='max_guests',
            field=models.IntegerField(default=2, help_text='Maximum number of guests', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nightly rental rate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Sale price or base price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('commercial', 'Commercial'), ('office', 'Office'), ('traditional_home', 'Traditional Home')], max_length=20),
        ),
    ]
