# Generated by Django 5.2.8 on 2025-12-03 09:33

import config.firebase_storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_amenities_property_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=config.firebase_storage_backend.FirebaseStorage(location='properties'), upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(storage=config.firebase_storage_backend.FirebaseStorage(location='properties/images'), upload_to='properties/images/'),
        ),
    ]
