# Generated by Django 5.2.8 on 2025-12-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_main_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('airbnb', 'Airbnb'), ('commercial', 'Commercial'), ('office', 'Office'), ('traditional_home', 'Traditional Home')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending'), ('development', 'Development')], default='available', max_length=20),
        ),
    ]
