# Generated by Django 4.2.7 on 2025-12-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_heroimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroImage',
        ),
        migrations.AddField(
            model_name='property',
            name='development_type',
            field=models.CharField(blank=True, choices=[('new_development', 'New Development'), ('off_plan', 'Off-Plan'), ('pre_launch', 'Pre-Launch'), ('under_construction', 'Under Construction'), ('completed', 'Completed'), ('gated_community', 'Gated Community'), ('mixed_use_development', 'Mixed-Use Development')], help_text="Type of development (only applicable when status is 'development')", max_length=30, null=True),
        ),
    ]
