# Generated by Django 5.0.3 on 2026-03-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_delete_heroimage_property_development_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(help_text='Number of bathrooms (comma-separated for multiple units)', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(help_text='Number of bedrooms (comma-separated for multiple units)', max_length=100),
        ),
    ]
