# Generated by Django 5.0.3 on 2026-03-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_bathrooms_alter_property_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
