# Generated by Django 5.2.13 on 2026-04-23 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_populate_property_slugs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='property',
            name='rental_duration',
            field=models.CharField(blank=True, choices=[('short_term', 'Short-term (1-30 days)'), ('long_term', 'Long-term (30+ days)'), ('both', 'Both Short & Long-term')], help_text='Rental duration type for Airbnb properties', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
