# Generated by Django 4.2.7 on 2025-12-03 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title', max_length=200)),
                ('message', models.TextField(help_text='Announcement message/content')),
                ('is_major', models.BooleanField(default=False, help_text='Major announcements appear as popups. Non-major announcements are only shown in the announcements page.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active announcements are displayed')),
                ('display_duration', models.IntegerField(default=5, help_text='How long the popup stays visible (in seconds). Only applies to major announcements.')),
                ('start_date', models.DateTimeField(blank=True, help_text='When to start showing this announcement (leave empty for immediate)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing this announcement (leave empty for no end date)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
