# Generated by Django 4.2.7 on 2025-12-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the announcement', null=True, upload_to='announcements/'),
        ),
    ]
