# Generated by Django 4.2.7 on 2025-12-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='url',
            field=models.URLField(blank=True, help_text='Optional URL to redirect users when announcement is clicked', max_length=500, null=True),
        ),
    ]
