# Generated by Django 4.2.7 on 2025-12-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='display_duration',
            field=models.IntegerField(default=5, help_text='Display duration in seconds (for reference). Major announcements are displayed in a banner below the navbar until dismissed.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_major',
            field=models.BooleanField(default=False, help_text='Major announcements appear as banners below the navbar. Non-major announcements are only shown in the announcements page.'),
        ),
    ]
