# Generated by Django 4.2.7 on 2025-12-04 05:22

import config.firebase_storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('business', 'Business'), ('tech', 'Tech'), ('real_estate', 'Real Estate'), ('updates', 'Updates'), ('market_analysis', 'Market Analysis'), ('investment', 'Investment'), ('lifestyle', 'Lifestyle'), ('other', 'Other')], default='other', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, help_text='Article thumbnail image', null=True, storage=config.firebase_storage_backend.FirebaseStorage(location='article_thumbnails'), upload_to='article_thumbnails/')),
                ('content', models.TextField(help_text='Rich text content')),
                ('excerpt', models.CharField(help_text='Short preview text', max_length=500)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'real estate, investment, nairobi')", max_length=500)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
