from django.urls import path
from .views import (
    dashboard_login,
    dashboard_logout,
    get_current_user,
    dashboard_stats,
    property_analytics,
    recent_activity,
    top_performers,
    create_property,
    update_property,
    delete_property,
    create_agent,
    update_agent,
    delete_agent,
    create_user,
    update_user,
    delete_user,
    change_password,
    agent_analytics,
    list_properties,
    get_property,
    list_pages,
    get_page,
    create_page,
    update_page,
    delete_page,
    list_announcements,
    get_major_announcements,
    list_all_announcements,
    get_announcement,
    create_announcement,
    update_announcement,
    delete_announcement,
    list_testimonials,
    list_all_testimonials,
    get_testimonial,
    create_testimonial,
    update_testimonial,
    delete_testimonial,
    list_events,
    list_all_events,
    get_event,
    get_event_admin,
    create_event,
    update_event,
    delete_event,
    list_articles,
    get_article,
    create_article,
    update_article,
    delete_article,
)

urlpatterns = [
    path('login/', dashboard_login, name='dashboard-login'),
    path('logout/', dashboard_logout, name='dashboard-logout'),
    path('user/', get_current_user, name='current-user'),
    path('change-password/', change_password, name='change-password'),
    path('stats/', dashboard_stats, name='dashboard-stats'),
    path('analytics/', property_analytics, name='property-analytics'),
    path('agent-analytics/', agent_analytics, name='agent-analytics'),
    path('activity/', recent_activity, name='recent-activity'),
    path('top-performers/', top_performers, name='top-performers'),
    path('properties/', list_properties, name='list-properties'),
    path('properties/<int:property_id>/', get_property, name='get-property'),
    path('properties/create/', create_property, name='create-property'),
    path('properties/<int:property_id>/update/', update_property, name='update-property'),
    path('properties/<int:property_id>/delete/', delete_property, name='delete-property'),
    path('agents/create/', create_agent, name='create-agent'),
    path('agents/<int:agent_id>/update/', update_agent, name='update-agent'),
    path('agents/<int:agent_id>/delete/', delete_agent, name='delete-agent'),
    path('users/create/', create_user, name='create-user'),
    path('users/<int:user_id>/update/', update_user, name='update-user'),
    path('users/<int:user_id>/delete/', delete_user, name='delete-user'),
    path('pages/', list_pages, name='list-pages'),
    path('pages/<int:page_id>/', get_page, name='get-page'),
    path('pages/create/', create_page, name='create-page'),
    path('pages/<int:page_id>/update/', update_page, name='update-page'),
    path('pages/<int:page_id>/delete/', delete_page, name='delete-page'),
    path('announcements/', list_all_announcements, name='list-all-announcements'),
    path('announcements/<int:announcement_id>/', get_announcement, name='get-announcement'),
    path('announcements/create/', create_announcement, name='create-announcement'),
    path('announcements/<int:announcement_id>/update/', update_announcement, name='update-announcement'),
    path('announcements/<int:announcement_id>/delete/', delete_announcement, name='delete-announcement'),
    path('announcements/public/', list_announcements, name='list-announcements'),
    path('announcements/public/major/', get_major_announcements, name='get-major-announcements'),
    path('testimonials/', list_all_testimonials, name='list-all-testimonials'),
    path('testimonials/<int:testimonial_id>/', get_testimonial, name='get-testimonial'),
    path('testimonials/create/', create_testimonial, name='create-testimonial'),
    path('testimonials/<int:testimonial_id>/update/', update_testimonial, name='update-testimonial'),
    path('testimonials/<int:testimonial_id>/delete/', delete_testimonial, name='delete-testimonial'),
    path('testimonials/public/', list_testimonials, name='list-testimonials'),
    path('events/', list_all_events, name='list-all-events'),
    path('events/<int:event_id>/', get_event_admin, name='get-event-admin'),
    path('events/create/', create_event, name='create-event'),
    path('events/<int:event_id>/update/', update_event, name='update-event'),
    path('events/<int:event_id>/delete/', delete_event, name='delete-event'),
    path('events/public/', list_events, name='list-events'),
    path('events/public/<int:event_id>/', get_event, name='get-event'),
    path('articles/', list_articles, name='list-articles'),
    path('articles/<int:article_id>/', get_article, name='get-article'),
    path('articles/create/', create_article, name='create-article'),
    path('articles/<int:article_id>/update/', update_article, name='update-article'),
    path('articles/<int:article_id>/delete/', delete_article, name='delete-article'),
]
